services:
  postgres:
    image: postgres:17-alpine
    ports:
      - 127.0.0.1:5432:5432
    container_name: truck_bdd
    environment:
      - POSTGRES_USER=truck
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=truck
  nginx:
    image: nginx:alpine
    container_name: nginx_alpine
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./workspace/FrontDemo/dist/front-demo/browser/:/usr/share/nginx/html
      - ./nginx/conf:/etc/nginx/conf.d
  springboot-app:
    image: openjdk:21-jdk-slim
    container_name: springboot_container
    volumes:
      - ./workspace/RaphlysDemo/build/libs/:/app/
    command: ["java", "-jar", "/app/RaphlysDemo-0.0.1-SNAPSHOT.jar"]

